---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - stack.kachi-bits
  resources:
  - appstacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stack.kachi-bits
  resources:
  - appstacks/finalizers
  verbs:
  - update
- apiGroups:
  - stack.kachi-bits
  resources:
  - appstacks/status
  verbs:
  - get
  - patch
  - update
