apiVersion: stack.kachi-bits/v1alpha1
kind: AppStack
metadata:
  labels:
    app.kubernetes.io/name: appstack
    app.kubernetes.io/instance: appstack-sample
    app.kubernetes.io/part-of: kube-builder
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kube-builder
  name: appstack-sample
spec:
  service:
    ports:
    - port: 80
  workload:
    image: nginx
    replicas: 2
    env:
      - name: test
        value: test
  
  ingress:
   ingressClass: mamad
   rules:
   - host: mamamd.com
     paths:
     - path: "/"
       port: 80
       pathType: Prefix

